# ==========================================
# CONFIGURACI√ìN GENERAL
# ==========================================
palette = "tokyo_night"
add_newline = true

# Lado Izquierdo: Limpio y enfocado en la navegaci√≥n y Git
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$aws\
$gcloud\
$azure\
$line_break\
$character"""

# Lado Derecho: Tecnolog√≠as, Infraestructura y Tiempo
right_format = """
$python\
$java\
$nodejs\
$rust\
$docker_context\
$kubernetes\
$terraform\
$cmd_duration\
"""

# ==========================================
# CORE & GIT
# ==========================================
[character]
success_symbol = "[‚ùØ](bold green)"
error_symbol = "[‚ùØ](bold red)"
vimcmd_symbol = "[‚ùÆ](bold green)"

[directory]
style = "blue bold"
read_only = " Û∞åæ"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "Ôêò "
style = "purple"

[git_commit]
tag_symbol = ' Ôêí '

[git_status]
style = "red"
conflicted = "üè≥"
ahead = "Ó™°"
behind = "Ó™ö"
diverged = "Û∞òñ"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "¬ª"
deleted = "x"


[cmd_duration]
min_time = 2000
style = "dark_gray"
format = "[$duration]($style) "

# ==========================================
# DATA ENGINEERING & PROGRAMACI√ìN
# ==========================================
[python]
style = "dark_blue"
symbol = 'Óàµ '
# uv usa .venv por defecto, Starship lo detectar√° autom√°ticamente como virtualenv
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[java]
symbol = "Û∞Ö∂ "
style = "red"
format = "[$symbol($version )]($style)"

[nodejs]
symbol = "Óúò "
style = "green"
format = "[$symbol($version )]($style)"

[rust]
symbol = "Û±òó "
style = "orange"
format = "[$symbol($version )]($style)"

# ==========================================
# INFRAESTRUCTURA & CLOUD (DevOps / DataOps)
# ==========================================
[terraform]
symbol = "Û±Å¢ "
style = "purple"
format = "[$symbol$workspace]($style) "

[aws]
symbol = "Û∞∏è "
style = "orange"
format = '[$symbol($profile )(\($region\) )]($style)'

[gcloud]
symbol = "Û±á∂ "
style = "dark_gray"
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[azure]
symbol = "Û∞†Ö "
style = "blue"
format = '[$symbol($subscription)]($style) '

[kubernetes]
symbol = "Û±Éæ "
style = "cyan"
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[docker_context]
symbol = "Ôåà "
style = "blue"
format = "[$symbol$context]($style) "

# ==========================================
# PALETA DE COLORES (Tokyo Night)
# ==========================================
[palettes.tokyo_night]
red = '#f7768e'
orange = '#ff9e64'
yellow = '#e0af68'
beige = '#cfc9c2'
green = '#9ece6a'
aqua = '#73daca'
light_cyan = '#b4f9f8'
cyan = '#2ac3de'
blue = '#7dcfff'
dark_blue = '#7aa2f7'
purple = '#bb9af7'
foreground = '#c0caf5'
light_gray = '#a9b1d6'
gray = '#9aa5ce'
dark_gray = '#565f89'
darker_gray = '#414868'
background = '#1a1b26'
